CREATE TABLE [dbo].[TRANSACTIONS] (
    [TRANSACTION_ID]             INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    [ACCOUNT_ID]                 INT NOT NULL,
    [TRANSACTION_DATE]           DATETIME NOT NULL,
    [TRANSACTION_TYPE]           VARCHAR (50) NOT NULL,
    [AMOUNT]                     DECIMAL (10, 2) NOT NULL,
    [BALANCE_AFTER_TRANSACTION]  DECIMAL (10, 2) NOT NULL,
    [DESCRIPTION]                TEXT NULL,
    FOREIGN KEY ([ACCOUNT_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACCOUNT_ID])
);
select * from TRANSACTIONS